# API version yang digunakan untuk object statefulset
apiVersion: apps/v1
# Jenis object yang akan dibuat berupa statefulset
kind: StatefulSet
# Metadata untuk memberikan nama dan label pada object statefulset
metadata:
  # Memberikan nama object mongo
  name: mongo
  # Memberikan label object app: mongo
  labels:
    app: mongo
# Memberikan spesifikasi untuk object statefulset
spec:
  # Menentukan bahwa replica pod berjumlah 1
  replicas: 1
  # Menggunakan selector untuk mengidentifikasi pod yang memiliki app: mongo && tier: backend (harus sama seperti service)
  selector:
    matchLabels:
      app: mongo
      tier: backend
  # Memberikan nama service mongo
  serviceName: mongo
  # Tambahan menunggu selama 10 detik setelah pod sudah ready
  minReadySeconds: 10
  # Memberikan pod template untuk memberikan metadata dan spesifikasi container
  template:
    # Memberikan metadata berupa label app: mongo && tier: backend
    metadata:
      labels:
        app: mongo
        tier: backend
    # Memberikan spesifikasi container pada pod
    spec:
      # Waktu yang dibutuhkan untuk kubernetes menunggu untuk app shutdown
      terminationGracePeriodSeconds: 10
      # Menjalankan container dengan nama mongo
      containers:
        - name: mongo
          # Mengambil image mongo:4.4-rc default dari docker hub
          image: mongo:4.4-rc
          # Menentukan environment variable pada container
          env:
            - name: MONGO_INITDB_ROOT_USERNAME_FILE
              value: /etc/mongo-credentials/MONGO_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD_FILE
              value: /etc/mongo-credentials/MONGO_ROOT_PASSWORD
          # Menentukan container berjalan pada port 27017
          ports:
            - containerPort: 27017
              name: mongo
          # Menentukan nama dan path mounting volume
          volumeMounts:
            - name: mongo-persistent-volume
              mountPath: /data/db
            - name: mongo-config-map
              mountPath: /config
            - name: mongo-secrets
              mountPath: /etc/mongo-credentials     
      # Mendeklarasikan volume yang digunakan
      volumes:
        - name: mongo-persistent-volume
          persistentVolumeClaim:
            claimName: mongo-pv-claim
        - name: mongo-config-map
          configMap:
            name: mongo-config
            items: 
              - key: mongo.conf
                path: mongo.conf
        - name: mongo-secrets
          secret:
            secretName: mongo-secret