# API version yang digunakan untuk object deployment
apiVersion: apps/v1
# Jenis object yang akan dibuat berupa deployment
kind: Deployment
# Metadata untuk memberikan nama dan label pada object deployment
metadata:
  # Memberikan nama object karsajobs
  name: karsajobs
  # Memberikan label object app: karsajobs
  labels:
    app: karsajobs
# Memberikan spesifikasi untuk object deployment
spec:
  # Menentukan bahwa replica pod berjumlah 3
  replicas: 3
  # Menggunakan selector untuk mengidentifikasi pod yang memiliki label app: karsajobs (harus sama seperti service)
  selector:
    matchLabels:
      app: karsajobs
  # Memberikan pod template untuk memberikan metadata dan spesifikasi container
  template:
    # Memberikan metadata berupa label app: karsajobs (Label untuk backend application)
    metadata:
      labels:
        app: karsajobs 
    # Memberikan spesifikasi container pada pod
    spec:
      # Menjalankan container dengan nama karsajobs
      containers:
        - name: karsajobs
          # Mengambil image ghcr.io/saviranurul/karsajobs:latest dari github packages
          image: ghcr.io/saviranurul/karsajobs:latest 
          # Menentukan container berjalan pada port 8080
          ports:
            - containerPort: 8080 
          # Menentukan environment variable pada container
          env:
            - name: APP_PORT
              value: "8080"
            - name: MONGO_HOST
              value: "mongo"
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_ROOT_USERNAME
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_ROOT_PASSWORD